on:
  push:
     branches:
       - dev
  repository_dispatch: pong

name: render-book-en

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          
      - name: ACKNOWLEDGE - Dispatch response to received PONG
        if: github.event.action == 'pong'
        run: |
          curl -X POST https://api.github.com/repos/QCBSRworkshops/templateWorkshops/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "acknowledged", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          
  book-en-job:
    name: Render the book for this workshop in bookdown
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: book-en
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup R  
        uses: r-lib/actions/setup-r@v1
        
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key:  r-${{ hashFiles('DESCRIPTION') }}

      - name: Install pandoc and pandoc citeproc
        uses: r-lib/actions/setup-pandoc@v1
        
      - name: Install R packages and dependencies
        run: |
          Rscript -e 'options(Ncpus = 4); pkgs = c("rmarkdown", "bookdown", "formatR"); 
          if(length(new.pkgs <- setdiff(pkgs, rownames(installed.packages())))) install.packages(new.pkgs)'        
      
      - name: Install pandoc and pandoc citeproc
        uses: r-lib/actions/setup-pandoc@v1
        
      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("rmarkdown", "bookdown", "formatR"))'
        
      - name: Render the book using bookdown
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
        
      - uses: actions/upload-artifact@v1
        with:
          name: book-en
          path: book-en/
  
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for an ACCESS_TOKEN

  checkout-and-deploy:
   name: Checkout and deploy the book within the master repository
   runs-on: ubuntu-latest
   needs: book-en-job
   
   steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
         # Artifact name
         name: book-en # optional
         # Destination path
         path: book-en/ # optional

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: book-en/_book/
          TARGET_FOLDER: book-en # The folder the action should deploy
          CLEAN: true

