on:
  push:
     branches:
       - dev

  
name: render-book-fr

jobs:
  book-fr-job:
    name: Render the book for this workshop in bookdown
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: book-fr
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup R  
        uses: r-lib/actions/setup-r@v1
        
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key:  r-${{ hashFiles('DESCRIPTION') }}

      - name: Install pandoc and pandoc citeproc
        uses: r-lib/actions/setup-pandoc@v1
        
      - name: Install R packages and dependencies
        run: |
          Rscript -e 'options(Ncpus = 4); pkgs = c("rmarkdown", "bookdown", "formatR"); 
          if(length(new.pkgs <- setdiff(pkgs, rownames(installed.packages())))) install.packages(new.pkgs)'
         
      - name: Install pandoc and pandoc citeproc
        uses: r-lib/actions/setup-pandoc@v1
        
      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("rmarkdown", "bookdown", "formatR"))'
        
      - name: Render the book using bookdown
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
        
      - uses: actions/upload-artifact@v1
        with:
          name: book-fr
          path: book-fr/
  
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy

  checkout-and-deploy:
   name: Checkout and deploy the book within the master repository
   runs-on: ubuntu-latest
   needs: book-fr-job
   
   steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
         # Artifact name
         name: book-fr # optional
         # Destination path
         path: book-fr/ # optional

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: book-fr/_book/
          TARGET_FOLDER: book-fr # The folder the action should deploy
          CLEAN: true
